Repository bonsai-rx/sgen, pull requests merged in 2023-10, with the labels that each got.

#4 Ensure consistent array instance type
  Bonsai.Sgen/Program.cs
  Directory.Build.props
Labels: fix

#1 Add instructions to README file
  README.md
Labels: documentation

#5 Make schema option required
  Bonsai.Sgen/Program.cs
Labels: feature

#6 Publish first release
  Directory.Build.props
  README.md
Labels: feature
